
steps:
  # Step for Build Container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/synapses-323217/github.com/misbahhassan08/FirebaseAuthTest:$COMMIT_SHA","."]
  
  # Step for Push Container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/synapses-323217/github.com/Misbahhassan08/FirebaseAuthTest:$COMMIT_SHA"]
    
 # Deploy image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run' ,'deploy',  'firebaseauthtest', '--region=us-central1',  '--platform=managed', '--image=gcr.io/cobalt-catalyst-263401/Misbahhassan08/FirebaseAuthTest:$COMMIT_SHA']